import type { FileExtension, FileDetails } from "./file_types";

export let FILE_TYPES: Record<FileExtension, FileDetails> = {
  // Office Documents
  pptx: {
    extn: "pptx",
    name: "PowerPoint Presentation",
    filetype: "office",
    backgroundcolor: "#D24625",
    color: "white",
    openwith: "PowerPoint",
    preview: false,
  },
  ppt: {
    extn: "ppt",
    name: "PowerPoint 97-2003",
    filetype: "office",
    backgroundcolor: "#D24625",
    color: "white",
    openwith: "PowerPoint",
    preview: false,
  },
  docx: {
    extn: "docx",
    name: "MS Word Document",
    filetype: "office",
    backgroundcolor: "#243C80",
    color: "white",
    openwith: "Word",
    preview: false,
  },
  doc: {
    extn: "doc",
    name: "Word 97-2003",
    filetype: "office",
    backgroundcolor: "#243C80",
    color: "white",
    openwith: "Word",
    preview: false,
  },
  xlsx: {
    extn: "xlsx",
    name: "Excel Sheet",
    filetype: "office",
    backgroundcolor: "#217346",
    color: "white",
    openwith: "Excel",
    preview: false,
  },
  xls: {
    extn: "xls",
    name: "Excel 97-2003",
    filetype: "office",
    backgroundcolor: "#217346",
    color: "white",
    openwith: "Excel",
    preview: false,
  },
  pdf: {
    extn: "pdf",
    name: "PDF Document",
    filetype: "pdf",
    backgroundcolor: "#DC1D00",
    color: "white",
    openwith: "PDF Reader",
    preview: true,
  },
  eml: {
    extn: "eml",
    name: "Email",
    filetype: "office",
    backgroundcolor: "#243C80",
    color: "white",
    openwith: "Outlook",
    preview: false,
  },
  otf: {
    extn: "otf",
    name: "Email",
    filetype: "office",
    backgroundcolor: "#243C80",
    color: "white",
    openwith: "Outlook",
    preview: false,
  },

  odt: {
    extn: "odt",
    name: "OpenDocument Text",
    filetype: "office",
    backgroundcolor: "#243C80",
    color: "white",
    openwith: "LibreOffice",
    preview: false,
  },
  ods: {
    extn: "ods",
    name: "OpenDocument Spreadsheet",
    filetype: "office",
    backgroundcolor: "#217346",
    color: "white",
    openwith: "LibreOffice",
    preview: false,
  },
  odp: {
    extn: "odp",
    name: "OpenDocument Presentation",
    filetype: "office",
    backgroundcolor: "#D24625",
    color: "white",
    openwith: "LibreOffice",
    preview: false,
  },

  // Images
  jpg: {
    extn: "jpg",
    name: "JPEG Image",
    filetype: "img",
    backgroundcolor: "#FF6B35",
    color: "black",
    openwith: "Image Viewer",
    preview: true,
  },
  jpeg: {
    extn: "jpeg",
    name: "JPEG Image",
    filetype: "img",
    backgroundcolor: "#FF6B35",
    color: "black",
    openwith: "Image Viewer",
    preview: true,
  },
  png: {
    extn: "png",
    name: "PNG Image",
    filetype: "img",
    backgroundcolor: "#004B87",
    color: "white",
    openwith: "Image Viewer",
    preview: true,
  },
  svg: {
    extn: "svg",
    name: "SVG Vector",
    filetype: "img",
    backgroundcolor: "#FFB81C",
    color: "black",
    openwith: "Image Viewer",
    preview: true,
  },
  gif: {
    extn: "gif",
    name: "GIF Image",
    filetype: "img",
    backgroundcolor: "#9E1FE8",
    color: "white",
    openwith: "Image Viewer",
    preview: true,
  },
  avif: {
    extn: "avif",
    name: "AVIF Image",
    filetype: "img",
    backgroundcolor: "#FFB900",
    color: "black",
    openwith: "Image Viewer",
    preview: true,
  },
  webp: {
    extn: "webp",
    name: "WebP Image",
    filetype: "img",
    backgroundcolor: "#009CDE",
    color: "white",
    openwith: "Image Viewer",
    preview: true,
  },
  bmp: {
    extn: "bmp",
    name: "Bitmap Image",
    filetype: "img",
    backgroundcolor: "#0078D4",
    color: "white",
    openwith: "Image Viewer",
    preview: true,
  },
  tiff: {
    extn: "tiff",
    name: "TIFF Image",
    filetype: "img",
    backgroundcolor: "#8B4513",
    color: "white",
    openwith: "Image Viewer",
    preview: true,
  },
  ico: {
    extn: "ico",
    name: "Icon File",
    filetype: "img",
    backgroundcolor: "#FFB900",
    color: "black",
    openwith: "Image Viewer",
    preview: true,
  },

  // Video
  mp4: {
    extn: "mp4",
    name: "MPEG-4 Video",
    filetype: "video",
    backgroundcolor: "#9E1FE8",
    color: "white",
    openwith: "Video Player",
    preview: true,
  },
  mkv: {
    extn: "mkv",
    name: "Matroska Video",
    filetype: "video",
    backgroundcolor: "#9E1FE8",
    color: "white",
    openwith: "Video Player",
    preview: true,
  },
  mov: {
    extn: "mov",
    name: "QuickTime Movie",
    filetype: "video",
    backgroundcolor: "#9E1FE8",
    color: "white",
    openwith: "Video Player",
    preview: true,
  },
  avi: {
    extn: "avi",
    name: "AVI Video",
    filetype: "video",
    backgroundcolor: "#9E1FE8",
    color: "white",
    openwith: "Video Player",
    preview: true,
  },
  webm: {
    extn: "webm",
    name: "WebM Video",
    filetype: "video",
    backgroundcolor: "#639",
    color: "white",
    openwith: "Video Player",
    preview: true,
  },
  flv: {
    extn: "flv",
    name: "Flash Video",
    filetype: "video",
    backgroundcolor: "#FF0000",
    color: "white",
    openwith: "Video Player",
    preview: false,
  },
  wmv: {
    extn: "wmv",
    name: "Windows Media Video",
    filetype: "video",
    backgroundcolor: "#0078D4",
    color: "white",
    openwith: "Windows Media Player",
    preview: true,
  },
  m4v: {
    extn: "m4v",
    name: "iTunes Video",
    filetype: "video",
    backgroundcolor: "#555555",
    color: "white",
    openwith: "Video Player",
    preview: true,
  },

  // Audio
  mp3: {
    extn: "mp3",
    name: "MP3 Audio",
    filetype: "audio",
    backgroundcolor: "#FF6B00",
    color: "white",
    openwith: "Media Player",
    preview: true,
  },
  wav: {
    extn: "wav",
    name: "WAV Audio",
    filetype: "audio",
    backgroundcolor: "#0078D4",
    color: "white",
    openwith: "Media Player",
    preview: true,
  },
  aac: {
    extn: "aac",
    name: "AAC Audio",
    filetype: "audio",
    backgroundcolor: "#555555",
    color: "white",
    openwith: "Media Player",
    preview: true,
  },
  flac: {
    extn: "flac",
    name: "FLAC Audio",
    filetype: "audio",
    backgroundcolor: "#FF6B6B",
    color: "black",
    openwith: "Media Player",
    preview: true,
  },
  ogg: {
    extn: "ogg",
    name: "OGG Audio",
    filetype: "audio",
    backgroundcolor: "#FF8C42",
    color: "black",
    openwith: "Media Player",
    preview: true,
  },
  m4a: {
    extn: "m4a",
    name: "iTunes Audio",
    filetype: "audio",
    backgroundcolor: "#555555",
    color: "white",
    openwith: "Media Player",
    preview: true,
  },
  wma: {
    extn: "wma",
    name: "Windows Media Audio",
    filetype: "audio",
    backgroundcolor: "#0078D4",
    color: "white",
    openwith: "Media Player",
    preview: true,
  },

  // Archives
  zip: {
    extn: "zip",
    name: "ZIP Archive",
    filetype: "archive",
    backgroundcolor: "#F7931E",
    color: "black",
    openwith: "Archive Manager",
    preview: false,
  },
  rar: {
    extn: "rar",
    name: "RAR Archive",
    filetype: "archive",
    backgroundcolor: "#D4AF37",
    color: "black",
    openwith: "WinRAR",
    preview: false,
  },
  "7z": {
    extn: "7z",
    name: "7-Zip Archive",
    filetype: "archive",
    backgroundcolor: "#E34C26",
    color: "white",
    openwith: "7-Zip",
    preview: false,
  },
  tar: {
    extn: "tar",
    name: "TAR Archive",
    filetype: "archive",
    backgroundcolor: "#FCC624",
    color: "black",
    openwith: "Archive Manager",
    preview: false,
  },
  gz: {
    extn: "gz",
    name: "GZIP Archive",
    filetype: "archive",
    backgroundcolor: "#FCC624",
    color: "black",
    openwith: "Archive Manager",
    preview: false,
  },

  // Documents/Text
  txt: {
    extn: "txt",
    name: "Text File",
    filetype: "document",
    backgroundcolor: "#333333",
    color: "white",
    openwith: "Text Editor",
    preview: false,
  },
  rtf: {
    extn: "rtf",
    name: "Rich Text Format",
    filetype: "document",
    backgroundcolor: "#666666",
    color: "white",
    openwith: "Text Editor",
    preview: false,
  },
  md: {
    extn: "md",
    name: "Markdown",
    filetype: "document",
    backgroundcolor: "#083FA1",
    color: "white",
    openwith: "Text Editor",
    preview: false,
  },
  csv: {
    extn: "csv",
    name: "CSV File",
    filetype: "document",
    backgroundcolor: "#217346",
    color: "white",
    openwith: "Spreadsheet",
    preview: false,
  },
  json: {
    extn: "json",
    name: "JSON File",
    filetype: "document",
    backgroundcolor: "#F7DF1E",
    color: "black",
    openwith: "Text Editor",
    preview: false,
  },
  xml: {
    extn: "xml",
    name: "XML File",
    filetype: "document",
    backgroundcolor: "#FF6B35",
    color: "black",
    openwith: "Text Editor",
    preview: false,
  },
  sql: {
    extn: "sql",
    name: "SQL File",
    filetype: "document",
    backgroundcolor: "#336791",
    color: "white",
    openwith: "Text Editor",
    preview: false,
  },

  // Code
  ts: {
    extn: "ts",
    name: "TypeScript",
    filetype: "code",
    backgroundcolor: "#3178C6",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  tsx: {
    extn: "tsx",
    name: "TypeScript React",
    filetype: "code",
    backgroundcolor: "#3178C6",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  js: {
    extn: "js",
    name: "JavaScript",
    filetype: "code",
    backgroundcolor: "#F7DF1E",
    color: "black",
    openwith: "Code Editor",
    preview: false,
  },
  jsx: {
    extn: "jsx",
    name: "JavaScript React",
    filetype: "code",
    backgroundcolor: "#61DAFB",
    color: "black",
    openwith: "Code Editor",
    preview: false,
  },
  html: {
    extn: "html",
    name: "HTML",
    filetype: "code",
    backgroundcolor: "#E34C26",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  css: {
    extn: "css",
    name: "CSS",
    filetype: "code",
    backgroundcolor: "#563D7C",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  scss: {
    extn: "scss",
    name: "SCSS",
    filetype: "code",
    backgroundcolor: "#C6538C",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  less: {
    extn: "less",
    name: "LESS",
    filetype: "code",
    backgroundcolor: "#1D365D",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  py: {
    extn: "py",
    name: "Python",
    filetype: "code",
    backgroundcolor: "#3776AB",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  java: {
    extn: "java",
    name: "Java",
    filetype: "code",
    backgroundcolor: "#007396",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  cpp: {
    extn: "cpp",
    name: "C++",
    filetype: "code",
    backgroundcolor: "#00599C",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  c: {
    extn: "c",
    name: "C",
    filetype: "code",
    backgroundcolor: "#A8B9CC",
    color: "black",
    openwith: "Code Editor",
    preview: false,
  },
  php: {
    extn: "php",
    name: "PHP",
    filetype: "code",
    backgroundcolor: "#777BB4",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  rb: {
    extn: "rb",
    name: "Ruby",
    filetype: "code",
    backgroundcolor: "#CC342D",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
  go: {
    extn: "go",
    name: "Go",
    filetype: "code",
    backgroundcolor: "#00ADD8",
    color: "white",
    openwith: "Code Editor",
    preview: false,
  },
};

export const FILE_INPUT_ACCEPT_STRINGS = {
  images: "image/jpeg,image/png,image/svg+xml,image/gif,image/webp,image/bmp,image/tiff,image/x-icon",
  video: "video/mp4,video/quicktime,video/x-msvideo,video/webm,video/x-flv,video/x-ms-wmv,video/x-matroska,.mkv,.mov,.avi,.m4v",
  audio: "audio/mpeg,audio/wav,audio/aac,audio/flac,audio/ogg,audio/mp4,audio/x-ms-wma,.mp3,.wav,.aac,.flac,.ogg,.m4a,.wma",
  documents:
    "application/pdf,application/msword,application/vnd.ms-excel,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.presentation,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.odt,.ods,.odp,.txt,.rtf,.csv,.json,.xml,.sql,.md",
  archives: "application/zip,application/x-rar-compressed,application/x-7z-compressed,application/x-tar,application/gzip,.zip,.rar,.7z,.tar,.gz,.tar.gz",
  code: ".ts,.tsx,.js,.cjs,.jsx,.html,.css,.scss,.less,.py,.java,.cpp,.c,.php,.rb,.go,text/plain", // this is not comprehensive
  all: "",
};
